version: '3.7'
services:
  web_dev:
    build: .
    ports:
    - "4000:4000"
    volumes:
    - .:/switch
    environment:
    - ENV=development
    - PORT=4000
    - IP=0.0.0.0
networks:
  default:
    name: switch